name: github workflows

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: list the files
          run: ls

        - name: read the file
          run: cat README.md